services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      /app/docker/entrypoint.sh
    env_file:
      - ../.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    depends_on:
      - green_power_postgres
      - green_power_redis
      - green_power_mongodb
    ports:
      - "8000:8000"

  mqtt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      python scripts/start_mqtt.py
    env_file:
      - ../.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    ports:
      - "7002:7002"

  tcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      python scripts/start_tcp.py
    env_file:
      - ../.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    ports:
      - "6000:6000"
      - "7001:7001"

  green_power_postgres:
    image: postgres:16
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:?POSTGRES_DB_NAME is required}
      POSTGRES_USER: ${POSTGRES_DB_USER:?POSTGRES_DB_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD:?POSTGRES_DB_PASSWORD is required}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  green_power_redis:
    image: redis:7

  green_power_mongodb:
    image: mongo:7
    env_file:
      - ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER:?MONGO_DB_USER is required}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD:?MONGO_DB_PASSWORD is required}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:?MONGO_DB_NAME is required}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongo_data:
